import { ArrowLeft, ArrowUpRight, FileText, ShieldCheck } from "lucide-react";
import { legalUpdated, projectContact } from "../lib/project";
import { useEffect } from "react";

const privacy = [
  ["Introduction", "Semester OS is designed around your ownership and privacy of academic information. The current product is local-first: the core workspace operates on your device and does not require an account. This policy explains what the application intentionally processes and stores."],
  ["Information you provide", "You may enter your name, university, academic program, level, semester, specialization, courses, timetable, rooms, attendance, lateness, assignments, exams, notes, study activity, progress, and preferences. You may also choose timetable images, PDFs, material plans, and image or video wallpapers. These are used to provide your academic workspace and appearance settings."],
  ["Local-first processing", "Academic information is designed to be processed and stored locally wherever reasonably possible. Normal local operation does not intentionally upload your semester information into a Semester OS student database. The app downloads its code, fonts, icons, and extraction tools from its host. Hosting providers may process ordinary request information, such as IP addresses and technical logs, under their own policies. This policy does not promise that infrastructure generates no logs."],
  ["Document import and ownership", "Documents you select are used to help construct your semester. PDF text extraction and English image OCR run locally using same-origin application assets and workers. Your source files and generated previews are held temporarily while you review the import, and are released when setup closes; source documents are not included in Semester OS backups. Importing a document does not transfer ownership to Semester OS. You remain responsible for having appropriate rights or authorization to use the material you provide."],
  ["Extraction accuracy", "OCR and timetable interpretation may make mistakes. Extracted values may be uncertain or missing. Review every course and session, correct mistakes, and confirm important times and other academic information against official university sources. Semester OS is an organizational tool, not the official university source."],
  ["Local storage and retention", "Semester OS uses IndexedDB, browser storage, service-worker caches, and local application storage for functionality and offline use. Academic records and preferences remain until you edit or delete them, reset the workspace, or the browser or device removes them. Recovery snapshots retained before replacement or restoration may contain earlier academic information; you can delete them in Settings. Clearing site data, losing a device, uninstalling or resetting an application, or browser storage eviction can cause information loss. Removing the installed app does not always clear the browser's site data."],
  ["Backups", "Exported Semester OS backup files may contain personal and academic semester information, preferences, and wallpaper. You control where these files are stored and whom you share them with. Backups are not encrypted by Semester OS. Keep them somewhere you trust and review them before sharing. Recovery snapshots are local copies, not remote backups."],
  ["Accounts", "The current local-first core does not require a Semester OS account, email address, password, remote student database, or cloud sync. There is no automatic cross-device synchronization. A project contact email, if configured, is a way to contact the maintainer, not an account requirement."],
  ["Analytics and advertising", "Semester OS does not intentionally use your academic information to build advertising profiles and does not sell student academic data. The current application does not include an analytics, advertising, or telemetry integration. If these features are introduced, this policy must be updated before they are relied on, with any specific choices or consent that are required."],
  ["University independence", "Semester OS is an independent software project unless explicitly stated otherwise. Supporting a university's timetable or material-plan format does not imply endorsement, sponsorship, or official affiliation. University names and trademarks remain the property of their respective owners."],
  ["Your control", "You can edit records, correct imported information before confirming a semester, export and restore backups, reset semester records, replace a semester, and delete local recovery points. Settings also provides a confirmed deletion of the local workspace and preferences. To remove service-worker caches and all site storage as well, use your browser's site-data controls. A deletion in this app does not remove backup files you saved elsewhere."],
  ["Security", "Semester OS minimizes unnecessary collection and transmission and validates data at local trust boundaries. No software, device, browser, or storage system is guaranteed to be completely secure. Protect your device and browser, install application updates, and keep independent backups. Someone with access to your browser profile may be able to access your local academic information."],
  ["Possible future cloud features", "Optional accounts, cloud backup, synchronization, notifications, or server-assisted document processing may be considered in future releases. If introduced, privacy disclosures must be updated. You should understand what information leaves your device before enabling such a feature. Any specific consent required for off-device processing must be presented for that feature, rather than hidden in a general policy acknowledgement."],
  ["Policy changes", "Changes to this policy will be published here with a revised Last Updated date. Material changes in processing will be explained before you enable the relevant new functionality. Review this page when updating the application."],
  ["Contact", "Use the project contact shown below for privacy questions. Do not send private academic documents or a full backup unless necessary and agreed. The production operator must configure a monitored project contact before a public launch."],
  ["Short summary", "Semester OS is built to be local-first. Your timetable and semester information are designed to stay on your device during normal local operation. No account is currently required. You control your backups and remain responsible for reviewing automatically extracted information and confirming important academic information with your university."],
] as const;
const terms = [
  ["Purpose and independence", "Semester OS is an independent academic organization tool. It is not an official ECU or university system, and timetable-format support does not imply university endorsement. Use official university sources for authoritative academic decisions."],
  ["Accuracy and your review", "OCR, document interpretation, and scheduling calculations can contain errors. Review and correct imported data before confirming your semester. Verify deadlines, times, rooms, attendance rules, and other important information with your university. The app does not detect physical presence; attendance and arrival records are entered by you."],
  ["Documents and your content", "You retain ownership of documents and content you provide. You are responsible for having the rights or authorization to use them. Do not provide malicious files, another person's private information without appropriate authority, or material you are not entitled to use."],
  ["Software and intellectual property", "Use and distribution of the application source are subject to the license, if any, published with the release. No new source-code license is granted by this draft page. Third-party dependencies have their own licenses. University names and trademarks belong to their respective owners."],
  ["Availability, storage, and backups", "Application and browser availability can change. Local information can be lost through browser-data clearing, device failure, storage eviction, or an unsuccessful update. Export regular backups and keep them securely. A service-worker cache or a local recovery point is not a substitute for an independent backup."],
  ["Acceptable use", "Use the application lawfully and respect other people's rights. Do not intentionally distribute malicious documents or backups, interfere with the application's hosting or other users, or abuse any future server-based processing service."],
  ["Warranties and liability — pending review", "Release-specific warranty disclaimers and any limitation of liability require qualified legal review and applicable-law assessment. This draft does not establish a liability cap, waive statutory rights, or claim an exclusion is enforceable in your jurisdiction."],
  ["Future accounts and cloud services", "The current core requires no account and has no cloud sync. Any future account, paid service, cloud processing, or synchronization feature will need appropriate additional terms and clear privacy disclosures before it is enabled."],
  ["Governing law and jurisdiction — pending review", "The operator's identity, governing law, dispute procedures, and jurisdiction have not been selected in this draft. These must be completed with qualified advice before a serious commercial or public launch. No jurisdiction is invented here."],
  ["Changes and contact", "The release's applicable Terms must be reviewed when product operation changes. Use the project contact below with questions. These Terms are a preparation draft and have not been represented as attorney-reviewed."],
] as const;

export function LegalLinks() { return <span className="legal-links"><a href="/privacy">Privacy Policy</a><span aria-hidden="true">·</span><a href="/terms">Terms of Use</a></span>; }
export function Contact() { return projectContact ? <a href={`mailto:${projectContact}`}>{projectContact}<ArrowUpRight size={14} /></a> : <span>Project contact is not yet configured for this build.</span>; }
export function AboutLegal() {
  return <section className="panel about-legal"><ShieldCheck size={26} /><div className="eyebrow">ABOUT / YOUR DATA</div><h2>Local-first. Yours to manage.</h2><p>No account required. Your semester data is designed to remain on your device during normal local use. PDF extraction and OCR run on this device.</p><p>Semester OS is an independent project. Verify important academic information with your university.</p><div className="legal-cards"><a href="/privacy"><ShieldCheck size={21} /><span><strong>Privacy Policy</strong><small>Understand local processing, storage, and your choices.</small></span><ArrowUpRight size={17} /></a><a href="/terms"><FileText size={21} /><span><strong>Terms of Use</strong><small>Preparation draft · release terms pending legal review.</small></span><ArrowUpRight size={17} /></a></div><p className="fine-print">Project contact: <Contact /></p></section>;
}
export function LegalPage({ page }: { page: "privacy" | "terms" }) {
  useEffect(() => { document.title = `${page === "privacy" ? "Privacy Policy" : "Terms of Use"} · Semester OS`; }, [page]);
  const isPrivacy = page === "privacy", sections = isPrivacy ? privacy : terms;
  return <div className="legal-shell"><a className="skip-link" href="#legal-content">Skip to content</a><div className="legal-atmosphere" aria-hidden="true" /><header className="legal-header"><a href="/" className="legal-brand">△ <span>semesteros</span></a><a href="/"><ArrowLeft size={15} /> Return to workspace</a></header>
    <main id="legal-content" tabIndex={-1}><div className="eyebrow">SEMESTER OS / {isPrivacy ? "YOUR INFORMATION" : "USING YOUR WORKSPACE"}</div><h1>Semester OS<br />{isPrivacy ? "Privacy Policy" : "Terms of Use"}<span className="accent-punctuation">.</span></h1><p className="legal-updated">Last Updated: {legalUpdated}{!isPrivacy && " · Preparation draft"}</p>
      <div className="legal-promise"><ShieldCheck size={23} /><div><strong>Local-first. No account required.</strong><p>Your semester data is designed to remain on your device during normal local use.</p></div></div>
      {!isPrivacy && <p className="legal-draft-note">This draft explains the product's intended use. Release terms, operator details, and jurisdiction remain pending qualified legal review.</p>}
      <div className="legal-layout"><nav aria-label="Policy contents"><strong>ON THIS PAGE</strong>{sections.map(([title], i) => <a key={title} href={`#section-${i + 1}`}>{String(i + 1).padStart(2, "0")} {title}</a>)}</nav><article>{sections.map(([title, content], i) => <section id={`section-${i + 1}`} key={title}><span className="legal-section-number">{String(i + 1).padStart(2, "0")}</span><h2>{title}</h2><p>{content}</p></section>)}<div className="legal-contact"><strong>Project contact</strong><Contact /></div></article></div>
    </main><footer className="legal-footer"><span>SEMESTER OS · YOUR SPACE. YOUR PACE.</span><LegalLinks /></footer></div>;
}
